name: Publish Docker Image

on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: docker-wasm
  VERSION: v1.0
jobs:
  buildImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@master
        with:
          platforms: wasi/wasm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: image=moby/buildkit:master
      
      - name: log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: actions/checkout@v2
      - name: Build Container image
        run: docker buildx build --platform wasi/wasm --tag ghcr.io/nabad600/docker-wasm:v1.0 . --push
